sudo: false
language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose pandas pyparsing six scikit-learn Cython pyqt
  - pip install -r requirements.txt

script:
  - nosetests